import time
import re
import os
from google import genai

# --- 1. DEFINE THE CLEANER FUNCTION ---
def clean_google_response(response_object):
    """
    Removes the ugly 'vertexaisearch' links generated by the AI
    and appends a clean list of sources from metadata.
    """
    raw_text = response_object.text
    
    # A. Force remove the ugly source list from the text
    # This deletes everything after "Sources:" or "References:"
    clean_text = re.sub(
        r'(?i)\n\s*(\*\*|###\s*)?(Sources|References|Citations).*', 
        '', 
        raw_text, 
        flags=re.DOTALL
    )
    
    # B. Extract CLEAN links from hidden metadata
    clean_links_text = ""
    try:
        if hasattr(response_object, 'grounding_metadata'):
            meta = response_object.grounding_metadata
            if hasattr(meta, 'web_search_sources') and meta.web_search_sources:
                clean_links_text = "\n\n**Sources:**\n"
                for i, src in enumerate(meta.web_search_sources, 1):
                    title = getattr(src, "title", "Source")
                    url = getattr(src, "uri", "#")  # .uri is the CLEAN link
                    clean_links_text += f"{i}. [{title}]({url})\n"
    except Exception:
        pass

    return clean_text.strip() + clean_links_text

# --- 2. MAIN SCRIPT ---
api_key = os.environ.get("GOOGLE_API_KEY", "AIzaSyDfok3taVXUnPqIci34TN9kWlhFoee28ps")
client = genai.Client(api_key=api_key)

print("🚀 Starting Deep Research...")
try:
    interaction = client.interactions.create(
        input="Just tell me the name of the drivers in F1 2026 season.",
        agent="deep-research-pro-preview-12-2025",
        background=True,
    )
except Exception as e:
    print(f"❌ Failed to start: {e}")
    exit(1)

print(f"🆔 ID: {interaction.id}")
print("⏳ Waiting for results...")

start_time = time.time()

while True:
    try:
        interaction = client.interactions.get(interaction.id)
    except Exception:
        time.sleep(20)
        continue

    elapsed = int((time.time() - start_time) / 60)
    print(f"[{elapsed}min] Status: {interaction.status}", end="\r")

    if interaction.status == "completed":
        print("\n\n✅ RESEARCH COMPLETE")
        
        last_output = interaction.outputs[-1]
        
        # --- 3. CALL THE CLEANER HERE ---
        final_output = clean_google_response(last_output)
        
        print("\n" + "="*60)
        print("📝 REPORT:")
        print("="*60)
        print(final_output)
        break

    elif interaction.status == "failed":
        print(f"\n❌ FAILED: {getattr(interaction, 'error', 'Unknown')}")
        break

    time.sleep(20)

print("\n🎉 Done!")
